---
- hosts: balancer
  sudo: yes
  remote_user: vagrant
  tasks:
      - name: nginxをインストール
        yum: name=nginx state=latest
      - name: /etc/nginx/nginx.confの設定
        copy:
          src: config/nginx.conf
          dest: /etc/nginx/
          owner: root
          mode: 0644
          backup: yes
      - name: /etc/nginx/conf.d/default.confの設定
        copy:
          src: config/default.conf
          dest: /etc/nginx/conf.d/
          owner: root
          mode: 0644
          backup: yes
        notify: nginxを再起動
  handlers:
      - name: nginxを再起動
        service: name=nginx state=restarted
